dist: bionic
sudo: required
services:
- docker
language: go
go:
  - "1.13.1"
addons:
  firefox: latest
cache:
  directories:
    - ${HOME}/cached-deps
env:
  global:
    - PATH=${HOME}/cached-deps:${PATH}
  matrix:
    - VARIANT=native
    - VARIANT=python
    - VARIANT=patch

install:
- ./etc/travis_install.sh
before_script:
- make docker-build-local
script:
- ./etc/travis_test.sh

after_failure:
- firefox -v
- geckodriver --version
- kubectl version
- kubectl get all
- kubectl describe pod -l app=pachd
- kubectl describe pod -l suite=pachyderm,app=etcd
- kubectl logs -l app=pachd | tail -n 100 
- kubectl logs -l app=jupyterhub | tail -n 100
